# Generated by Django 4.1.5 on 2023-01-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='confirm_password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='password'),
        ),
    ]
