# Generated by Django 4.1.5 on 2023-02-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0003_progressuser_alter_customuser_confirm_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('progress', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ProgressUser',
        ),
    ]
